//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCPFavThingsWApiLib.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LCPFavThingsWApiLib.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a About.
        /// </summary>
        public static string mabout {
            get {
                return ResourceManager.GetString("mabout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Access Token.
        /// </summary>
        public static string maccesstoken {
            get {
                return ResourceManager.GetString("maccesstoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Authenticated.
        /// </summary>
        public static string mauthenticated {
            get {
                return ResourceManager.GetString("mauthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Avatar.
        /// </summary>
        public static string mavatar {
            get {
                return ResourceManager.GetString("mavatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Category.
        /// </summary>
        public static string mcategory {
            get {
                return ResourceManager.GetString("mcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company.
        /// </summary>
        public static string mcompany {
            get {
                return ResourceManager.GetString("mcompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cover.
        /// </summary>
        public static string mcover {
            get {
                return ResourceManager.GetString("mcover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Created.
        /// </summary>
        public static string mcreated {
            get {
                return ResourceManager.GetString("mcreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Date of Account Created.
        /// </summary>
        public static string mdateaccreated {
            get {
                return ResourceManager.GetString("mdateaccreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Date Birthday.
        /// </summary>
        public static string mdatebirthday {
            get {
                return ResourceManager.GetString("mdatebirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Date Release.
        /// </summary>
        public static string mdaterelease {
            get {
                return ResourceManager.GetString("mdaterelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Description.
        /// </summary>
        public static string mdesc {
            get {
                return ResourceManager.GetString("mdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Duration.
        /// </summary>
        public static string mduration {
            get {
                return ResourceManager.GetString("mduration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email.
        /// </summary>
        public static string memail {
            get {
                return ResourceManager.GetString("memail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Expiration.
        /// </summary>
        public static string mexpiration {
            get {
                return ResourceManager.GetString("mexpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a First Name.
        /// </summary>
        public static string mfirstname {
            get {
                return ResourceManager.GetString("mfirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GameId.
        /// </summary>
        public static string mgamesid {
            get {
                return ResourceManager.GetString("mgamesid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Genre.
        /// </summary>
        public static string mgenre {
            get {
                return ResourceManager.GetString("mgenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Language.
        /// </summary>
        public static string mlanguage {
            get {
                return ResourceManager.GetString("mlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Last Name.
        /// </summary>
        public static string mlastname {
            get {
                return ResourceManager.GetString("mlastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Message.
        /// </summary>
        public static string mmessage {
            get {
                return ResourceManager.GetString("mmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MovieId.
        /// </summary>
        public static string mmoviesid {
            get {
                return ResourceManager.GetString("mmoviesid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password.
        /// </summary>
        public static string mpassword {
            get {
                return ResourceManager.GetString("mpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pin.
        /// </summary>
        public static string mpin {
            get {
                return ResourceManager.GetString("mpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Publisher.
        /// </summary>
        public static string mpublisher {
            get {
                return ResourceManager.GetString("mpublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Query Command.
        /// </summary>
        public static string mqrycmd {
            get {
                return ResourceManager.GetString("mqrycmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rating.
        /// </summary>
        public static string mrating {
            get {
                return ResourceManager.GetString("mrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Role.
        /// </summary>
        public static string mrole {
            get {
                return ResourceManager.GetString("mrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SGBD Service.
        /// </summary>
        public static string msgbdsrv {
            get {
                return ResourceManager.GetString("msgbdsrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Title.
        /// </summary>
        public static string mtitle {
            get {
                return ResourceManager.GetString("mtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token Id.
        /// </summary>
        public static string mtokenid {
            get {
                return ResourceManager.GetString("mtokenid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Token Info.
        /// </summary>
        public static string mtokeninfo {
            get {
                return ResourceManager.GetString("mtokeninfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total Seasons.
        /// </summary>
        public static string mtotalseasons {
            get {
                return ResourceManager.GetString("mtotalseasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TVSerieId.
        /// </summary>
        public static string mtvserieid {
            get {
                return ResourceManager.GetString("mtvserieid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UserAuthId.
        /// </summary>
        public static string muserauthid {
            get {
                return ResourceManager.GetString("muserauthid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User Id.
        /// </summary>
        public static string muserid {
            get {
                return ResourceManager.GetString("muserid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Username.
        /// </summary>
        public static string musername {
            get {
                return ResourceManager.GetString("musername", resourceCulture);
            }
        }
    }
}
